pipeline {
  agent { docker { image 'python:3.7.4' } }
  stages {
    stage('build') {
      steps {
        sh 'pip install -r requirements.txt'
      }
    }
    stage('lint and test') {
      steps {
        sh 'pylint --disable=R,C,W1203 app.py'
        sh 'python test.py'
      }   
    }
  }
}
    stage('deploy cluster')
    stage('deploy container using rolling deployment')
     environment {
    registry = "blohmeier/capstone-test1"
    registryCredential = ‘dockerhub’
  }
  }
}
